OBJNAME   := init
TARGETDIR := System
LDLIBS    := 
AUTOLIBS  := 
FILES     := init
NO_EXEC   := true
LDFLAGS   := $(LDFLAGS) -nostartfiles -static

include $(ROOT_DIR)/config/make_app.mk
include $(ROOT_DIR)/config/make_bottom.mk
