OBJNAME   := example
OBJTYPE   := device
TARGETDIR := Devs
LDLIBS    := c
GLOBAL    := LibBase
LOCAL     := *
FILES     := example_init beginio

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
