OBJNAME   := debug
OBJTYPE   := library
TARGETDIR := Libs
LDLIBS    := c
GLOBAL    := LibBase DebugBase
LOCAL     := *
FILES     := debug_init vbug

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
