OBJNAME   := utility
OBJTYPE   := library
TARGETDIR := Libs
LDLIBS    := c
GLOBAL    := LibBase ExecBase
LOCAL     := *
FILES     := utility_init callhookpkt

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
