OBJNAME   := dos
OBJTYPE   := library
TARGETDIR := Libs
LDLIBS    := c
AUTOLIBS  := exec
GLOBAL    := LibBase DOSBase
LOCAL     := *
FILES     := dos_init setioerr ioerr open close read write

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
