OBJNAME   := uuid
OBJTYPE   := library
TARGETDIR := Libs
LDLIBS    := 
GLOBAL    := LibBase UUIDBase
LOCAL     := *
FILES     := uuid_init uuid_clear uuid_copy

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
