OBJNAME   := uuid
OBJTYPE   := library
TARGETDIR := Libs
LDLIBS    := c
GLOBAL    := LibBase UUIDBase
LOCAL     := *
FILES     := uuid_init

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
