OBJNAME   := timer
OBJTYPE   := device
TARGETDIR := Devs
LDLIBS    := c
GLOBAL    := LibBase TimerBase
LOCAL     := *
FILES     := timer_init addtime subtime cmptime nanosleep getsystime getuptime beginio

include $(ROOT_DIR)/config/make_shared.mk
include $(ROOT_DIR)/config/make_bottom.mk
